### ISSUE TITLE
Partly broken

### ISSUE THREAD

**Issue by clem2** [Smile4ever/Translate-Now#1]
Bing works consistently. Google sometimes works, sometimes the text is not even sent. DeepL shows the wrong destination and source languages.
Firefox 129.0.2

**Comment by Smile4ever** [comment]
Version 5.0.4 https://github.com/Smile4ever/Translate-Now/commit/c4f12fc749a0403bf1313f2202aced6ca2f4c612 fixes these issues, it has been released at addons.mozilla.org.
